# Generated by Django 4.1.5 on 2023-01-16 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysports', '0003_sportclub'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sportclub',
            name='country',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
