# Generated by Django 4.1.5 on 2023-01-17 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysports', '0007_rename_turnament_tournament_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='year',
            field=models.CharField(max_length=10),
        ),
    ]
